"""
Assessment Questions Generator
Populates data/questions/assessment_questions.json with 160 high-quality MCQs
across 8 domains (20 questions per skill).
"""

import json
import os

def create_questions_bank():
    questions = []

    # 1. PYTHON (20 Questions)
    py_q = [
        ("What is the time complexity of looking up a key in a standard Python dictionary on average?",
         ["O(1)", "O(n)", "O(log n)", "O(n^2)"], "A",
         "Python dictionaries use hash tables, giving average-case O(1) lookup time."),
        ("Which of the following data structures in Python is immutable?",
         ["List", "Tuple", "Dictionary", "Set"], "B",
         "Tuples are immutable; once created, their elements cannot be changed or reassigned."),
        ("What keyword is used in Python to create a generator function?",
         ["return", "yield", "generate", "pass"], "B",
         "The 'yield' statement suspends function execution and yields a value back to the caller."),
        ("What will `bool([])` evaluate to in Python?",
         ["True", "False", "None", "TypeError"], "B",
         "Empty collections such as lists, tuples, and sets evaluate to False in boolean context."),
        ("Which module in Python standard library provides deep and shallow copy operations?",
         ["os", "sys", "copy", "clone"], "C",
         "The 'copy' module contains copy.copy() for shallow copy and copy.deepcopy() for deep copy."),
        ("What does the `*args` syntax in a function definition indicate?",
         ["Keyword arguments as dictionary", "Variable positional arguments as tuple", "Pointer dereference", "Mandatory arguments"], "B",
         "*args captures any number of non-keyword positional arguments as a tuple."),
        ("How do you handle exceptions gracefully in Python?",
         ["try-catch block", "try-except-finally block", "do-while block", "throw-catch block"], "B",
         "Python uses 'try' and 'except' blocks for catching and handling exceptions."),
        ("What is the output of `type(lambda x: x)`?",
         ["<class 'function'>", "<class 'lambda'>", "<class 'method'>", "<class 'object'>"], "A",
         "Lambda functions in Python are instances of the standard function type."),
        ("Which built-in function returns both the index and value during loop iteration?",
         ["range()", "zip()", "enumerate()", "sorted()"], "C",
         "enumerate() yields pairs of (index, item) during iteration."),
        ("What does `[x**2 for x in range(5) if x % 2 == 0]` produce?",
         ["[0, 4, 16]", "[1, 9]", "[0, 1, 4, 9, 16]", "[4, 16]"], "A",
         "Evaluates squares of even numbers in range(5): 0^2=0, 2^2=4, 4^2=16."),
        ("What is the difference between `==` and `is` in Python?",
         ["'==' checks value equality, 'is' checks object identity in memory", "'==' checks identity, 'is' checks value", "They are completely identical", "'is' is only for numbers"], "A",
         "'==' checks if values are equal, whereas 'is' checks if two variables point to the identical memory address."),
        ("Which Pandas method is used to inspect summary statistics of numerical columns?",
         ["df.info()", "df.describe()", "df.summary()", "df.stats()"], "B",
         "df.describe() computes count, mean, std, min, quartiles, and max."),
        ("What is a decorator in Python?",
         ["A CSS styling class", "A function that modifies the behavior of another function without modifying its source", "A design pattern for database transactions", "A syntax error"], "B",
         "Decorators wrap a function to extend its behavior dynamically."),
        ("How does Python manage memory allocation and deallocation automatically?",
         ["Manual pointers", "Reference counting and cyclical Garbage Collector", "JVM memory pool", "RAII only"], "B",
         "CPython utilizes reference counting complemented by a cyclical garbage collector."),
        ("What does `__init__` represent in a Python class?",
         ["Class destructor", "Instance initializer (constructor)", "Static method declaration", "Inheritance operator"], "B",
         "__init__ is called when a new object instance is instantiated to initialize attributes."),
        ("What is the output of `\"Python\"[::-1]`?",
         ["\"nohtyP\"", "\"Python\"", "\"P\"", "IndexError"], "A",
         "Slice syntax [::-1] reverses the string sequence."),
        ("Which NumPy function is used to create an array with 10 evenly spaced numbers between 0 and 1?",
         ["np.range(0, 1, 10)", "np.linspace(0, 1, 10)", "np.arange(0, 1, 10)", "np.spacing(0, 1, 10)"], "B",
         "np.linspace(start, stop, num) generates evenly spaced numbers over a specified interval."),
        ("What is a virtual environment used for in Python?",
         ["Running Docker containers", "Isolating package dependencies per project", "Compiling C code", "Speeding up CPU clocks"], "B",
         "Virtual environments isolate python dependencies for individual projects to avoid version conflicts."),
        ("In Pandas, which function is preferred to merge two DataFrames on a common key?",
         ["pd.concat()", "pd.merge()", "pd.append()", "pd.combine()"], "B",
         "pd.merge() performs database-style joins on common columns or indexes."),
        ("What does the Global Interpreter Lock (GIL) in CPython do?",
         ["Prevents all multi-threading", "Ensures only one thread executes Python bytecode at a time", "Encrypts interpreter files", "Blocks file I/O operations"], "B",
         "GIL is a mutex that protects access to Python objects, preventing multiple native threads from executing Python bytecodes at once.")
    ]

    # 2. SQL (20 Questions)
    sql_q = [
        ("Which SQL clause is used to filter groups created by GROUP BY?",
         ["WHERE", "HAVING", "ORDER BY", "FILTER"], "B",
         "HAVING filters groups of rows, whereas WHERE filters individual rows before grouping."),
        ("What is the primary difference between UNION and UNION ALL?",
         ["UNION retains duplicate rows, UNION ALL removes them", "UNION removes duplicate rows, UNION ALL preserves duplicates", "UNION only works on numbers", "There is no difference"], "B",
         "UNION runs a distinct operation to remove duplicates, while UNION ALL retains all rows."),
        ("Which JOIN returns all rows from the left table and matched rows from the right table?",
         ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN"], "B",
         "A LEFT JOIN returns all records from the left table and matched records from the right table."),
        ("What SQL constraint uniquely identifies each record in a database table?",
         ["FOREIGN KEY", "PRIMARY KEY", "CHECK", "NOT NULL"], "B",
         "A PRIMARY KEY constraint uniquely identifies each record and cannot contain NULL values."),
        ("Which SQL aggregate function computes the total sum of a numeric column?",
         ["COUNT()", "SUM()", "AVG()", "TOTAL()"], "B",
         "SUM() calculates the mathematical total sum of numeric values."),
        ("What window function ranks rows within a partition without leaving gaps for ties?",
         ["RANK()", "DENSE_RANK()", "ROW_NUMBER()", "NTILE()"], "B",
         "DENSE_RANK() assigns consecutive rank values without gaps when tied."),
        ("Which command is used to permanently remove a table structure and its data?",
         ["DELETE TABLE", "DROP TABLE", "TRUNCATE TABLE", "REMOVE TABLE"], "B",
         "DROP TABLE removes the entire table definition, constraints, and data permanently."),
        ("What is the purpose of an INDEX on a database column?",
         ["Enforces column data types", "Accelerates SELECT query data retrieval speed", "Saves storage disk space", "Encodes strings to binary"], "B",
         "Indexes (e.g. B-Trees) speed up lookups and joins at the cost of additional write overhead."),
        ("Which statement is classified as a Data Definition Language (DDL) command?",
         ["SELECT", "INSERT", "CREATE", "UPDATE"], "C",
         "CREATE, ALTER, and DROP are DDL commands that modify schema definitions."),
        ("What does `COALESCE(col1, col2, 'Default')` return?",
         ["Concatenation of all values", "The first non-null expression in the argument list", "Count of null values", "A boolean flag"], "B",
         "COALESCE returns the first non-null value from the list of provided arguments."),
        ("What is the default sort order of the `ORDER BY` clause?",
         ["DESC (Descending)", "ASC (Ascending)", "Random", "Natural insertion order"], "B",
         "ORDER BY defaults to ASC (ascending order) if not specified."),
        ("Which keyword eliminates duplicate rows from a query result set?",
         ["UNIQUE", "DISTINCT", "DIFFERENT", "ISOLATE"], "B",
         "SELECT DISTINCT removes duplicate rows from the query output."),
        ("How does `TRUNCATE` differ from `DELETE` without a WHERE clause?",
         ["TRUNCATE is a DDL operation that resets high-water marks and is generally faster", "DELETE is faster than TRUNCATE", "TRUNCATE can use WHERE conditions", "They are identical"], "A",
         "TRUNCATE is a fast DDL command that deallocates data pages rather than logging row deletions."),
        ("In SQL, what is a subquery in the FROM clause commonly known as?",
         ["Correlated query", "Derived table / Inline view", "Scalar subquery", "Trigger"], "B",
         "A subquery appearing in the FROM clause acts as a temporary derived table."),
        ("Which SQL operator checks whether a value matches any value in a list or subquery?",
         ["LIKE", "BETWEEN", "IN", "EXISTS"], "C",
         "The IN operator tests if an expression matches any item in a specified list."),
        ("What does ACID stand for in relational database management systems?",
         ["Atomicity, Consistency, Isolation, Durability", "Accuracy, Control, Integrity, Data", "Asynchronous, Concurrent, Isolated, Distributed", "Authentication, Cryptography, Integrity, Decoupling"], "A",
         "ACID properties guarantee reliable database transactions."),
        ("Which clause partitions data for window functions in SQL?",
         ["GROUP BY", "PARTITION BY", "DIVIDE BY", "SPLIT BY"], "B",
         "PARTITION BY divides the result set into partitions for window function calculations."),
        ("What is a FOREIGN KEY used for?",
         ["Encrypt sensitive data", "Enforce referential integrity between two related tables", "Speed up full text search", "Store external web URLs"], "B",
         "A foreign key establishes a link between columns in two tables and enforces referential integrity."),
        ("Which string function finds the length of a string in standard SQL?",
         ["LEN() / LENGTH()", "SIZEOF()", "COUNT_CHARS()", "STRLEN()"], "A",
         "LENGTH() (or LEN() in T-SQL) returns the character length of a string."),
        ("What is the result of `SELECT NULL = NULL` in SQL standard three-valued logic?",
         ["True", "False", "UNKNOWN / NULL", "Syntax Error"], "C",
         "In SQL three-valued logic, comparing NULL with NULL yields UNKNOWN (NULL), requiring `IS NULL`.")
    ]

    # 3. EXCEL (20 Questions)
    excel_q = [
        ("Which lookup function searches in any direction and does not require sorting or left-to-right restriction?",
         ["VLOOKUP", "HLOOKUP", "XLOOKUP", "LOOKUP"], "C",
         "XLOOKUP is modern, flexible, and can look up values in any direction without column index counting."),
        ("What does the `$` sign do in an Excel cell formula such as `$A$1`?",
         ["Formats cell as currency", "Creates an absolute cell reference that does not change when copied", "Converts text to numbers", "Multiplies value by 100"], "B",
         "$ locks the column and row coordinate, forming an absolute reference."),
        ("Which formula counts cells that meet a specific numerical or text criterion?",
         ["COUNT()", "COUNTA()", "COUNTIF()", "SUMIF()"], "C",
         "COUNTIF(range, criteria) counts cells satisfying the specified condition."),
        ("What Excel tool is best suited for aggregating, summarizing, and reorganizing large tables dynamically?",
         ["Conditional Formatting", "Pivot Table", "Data Validation", "Text to Columns"], "B",
         "Pivot Tables allow rapid multidimensional aggregation and grouping without writing formulas."),
        ("What error appears when Excel encounters a formula that attempts division by zero?",
         ["#N/A", "#VALUE!", "#DIV/0!", "#REF!"], "C",
         "#DIV/0! occurs when a formula attempts to divide a number by zero or an empty cell."),
        ("Which function calculates the arithmetic mean of numbers in a range?",
         ["MEDIAN()", "MODE()", "AVERAGE()", "MEAN()"], "C",
         "AVERAGE() computes the mathematical mean in Excel."),
        ("What does the INDEX-MATCH combination provide over classic VLOOKUP?",
         ["It works with both leftward lookups and resists column insertion breakage", "It only works on numbers", "It is 10 times slower", "It requires VBA macros"], "A",
         "INDEX-MATCH can search leftward and remains intact when columns are inserted or reordered."),
        ("Which feature restricts the type of data or values users can enter into a cell?",
         ["Data Validation", "Conditional Formatting", "Goal Seek", "Solver"], "A",
         "Data Validation allows rules like dropdown lists, whole numbers, or date constraints."),
        ("What formula combines text strings from different cells in modern Excel?",
         ["TEXTJOIN() / CONCAT()", "SUM()", "SPLIT()", "COMBINE()"], "A",
         "TEXTJOIN() combines strings with a delimiter and option to ignore empty cells."),
        ("Which function returns the current date and time dynamically in Excel?",
         ["TODAY()", "NOW()", "CURRENT()", "DATE()"], "B",
         "NOW() returns current date and time; TODAY() returns date only."),
        ("What keyboard shortcut opens the Excel Format Cells dialog box in Windows?",
         ["Ctrl + 1", "Ctrl + F", "Ctrl + Shift + P", "Alt + Enter"], "A",
         "Ctrl + 1 is the universal Windows shortcut to open Format Cells."),
        ("What is the purpose of Conditional Formatting in Excel?",
         ["Automate VBA code execution", "Format cells visually based on rules or cell values", "Password protect sheets", "Sort tables alphabetically"], "B",
         "Conditional Formatting highlights cells with colors or data bars based on defined rules."),
        ("What does `#N/A` error signify in VLOOKUP?",
         ["Formula syntax error", "Value not available / lookup value not found", "Memory overflow", "Column index out of bounds"], "B",
         "#N/A indicates that the lookup value cannot be found in the first column of the lookup range."),
        ("Which function checks whether multiple conditions are all True before returning True?",
         ["OR()", "AND()", "NOT()", "XOR()"], "B",
         "AND() returns True only if every logical condition supplied evaluates to True."),
        ("What tool in Excel allows you to find the required input value to achieve a specific target result?",
         ["Scenario Manager", "Goal Seek", "Pivot Chart", "Data Table"], "B",
         "Goal Seek is a what-if analysis tool that adjusts an input to reach a targeted outcome."),
        ("What function removes all extra spaces from text except for single spaces between words?",
         ["CLEAN()", "TRIM()", "STRIP()", "ERASE()"], "B",
         "TRIM() removes leading, trailing, and duplicate spaces from text strings."),
        ("How do you freeze the top row of an Excel sheet so it stays visible while scrolling?",
         ["View > Freeze Panes > Freeze Top Row", "Home > Freeze", "Insert > Panes", "Data > Lock Row"], "A",
         "The Freeze Top Row option under the View tab pins row 1 to the top of the view."),
        ("Which function returns the rank of a number in a list of numbers?",
         ["RANK.EQ()", "ORDER()", "INDEX()", "SORT()"], "A",
         "RANK.EQ() returns the statistical rank of a number within a specified array."),
        ("What does `IFERROR(VLOOKUP(...), \"Not Found\")` do?",
         ["Throws an error if found", "Intercepts errors from VLOOKUP and outputs \"Not Found\" instead", "Deletes the row on error", "Caches the error log"], "B",
         "IFERROR evaluates an expression and returns an alternative value if an error is raised."),
        ("Which chart type is best for displaying the distribution and spread of continuous numerical data in Excel?",
         ["Pie Chart", "Histogram / Box and Whisker", "Donut Chart", "Radar Chart"], "B",
         "Histograms and Box Plots display continuous frequency distributions and quartiles.")
    ]

    # 4. STATISTICS (20 Questions)
    stat_q = [
        ("Which measure of central tendency is least sensitive to extreme outliers?",
         ["Mean", "Median", "Mode", "Variance"], "B",
         "The median represents the 50th percentile and is robust against skewed outliers."),
        ("What does the p-value in a statistical hypothesis test represent?",
         ["The probability that the null hypothesis is true", "The probability of observing data as extreme as observed assuming null hypothesis is true", "The probability of making a Type II error", "The effect size of the test"], "B",
         "p-value measures the probability of obtaining test results at least as extreme under the null hypothesis."),
        ("What does a correlation coefficient of -0.85 indicate between two variables?",
         ["No correlation", "Weak negative correlation", "Strong negative linear relationship", "Curvilinear relationship"], "C",
         "Pearson r near -1 indicates a strong negative linear association."),
        ("What is the Central Limit Theorem (CLT)?",
         ["Sample mean always equals population mean", "Sampling distribution of sample means approaches normality as sample size increases regardless of population distribution", "All variables in nature are normally distributed", "Standard error increases with sample size"], "B",
         "CLT states the sampling distribution of means becomes approximately normal for large n."),
        ("What is a Type I error in hypothesis testing?",
         ["Failing to reject a false null hypothesis", "Rejecting a true null hypothesis (False Positive)", "Calculating the incorrect degrees of freedom", "Selecting non-random samples"], "B",
         "Type I error (alpha) occurs when a true null hypothesis is incorrectly rejected."),
        ("What is a Type II error in hypothesis testing?",
         ["Rejecting a true null hypothesis", "Failing to reject a false null hypothesis (False Negative)", "Sample size too small", "P-value equals zero"], "B",
         "Type II error (beta) occurs when a false null hypothesis is failed to be rejected."),
        ("What percentage of data falls within 2 standard deviations of the mean in a standard normal distribution?",
         ["Approximately 68%", "Approximately 95.4%", "Approximately 99.7%", "100%"], "B",
         "The empirical 68-95-99.7 rule states that ~95.4% of data falls within +/- 2 standard deviations."),
        ("What formula represents Variance in terms of Standard Deviation?",
         ["Variance = sqrt(Standard Deviation)", "Variance = (Standard Deviation)^2", "Variance = Standard Deviation / 2", "Variance = 2 * Standard Deviation"], "B",
         "Variance is mathematically the square of the standard deviation."),
        ("Which test is appropriate for comparing means between two independent normally distributed groups?",
         ["Chi-Square test", "Independent Two-Sample Student's t-test", "One-way ANOVA", "Kruskal-Wallis test"], "B",
         "Two-sample t-test compares the population means of two independent groups."),
        ("When is ANOVA (Analysis of Variance) used instead of multiple t-tests?",
         ["To compare means of 3 or more groups while controlling Family-Wise Type I error rate", "To compare categorical frequencies", "Only when sample size is less than 10", "To measure linear correlation"], "A",
         "ANOVA compares means across 3+ groups without inflating Type I error risk."),
        ("What does the Interquartile Range (IQR) represent?",
         ["Q1 + Q3", "Q3 - Q1 (Range of the middle 50% of the distribution)", "Maximum - Minimum", "Mean - Median"], "B",
         "IQR is Q3 (75th percentile) minus Q1 (25th percentile)."),
        ("Which probability distribution is commonly used to model the number of independent events occurring in a fixed interval of time?",
         ["Normal distribution", "Poisson distribution", "Uniform distribution", "Binomial distribution"], "B",
         "Poisson distribution models count data of events occurring at a constant average rate in fixed time/space."),
        ("What does Bayes' Theorem describe?",
         ["Joint probability of mutually exclusive events", "Conditional probability of an event given prior knowledge of conditions related to the event", "Probability of sampling without replacement", "Central tendency of skewed data"], "B",
         "P(A|B) = [P(B|A) * P(A)] / P(B), describing posterior probability updated with evidence."),
        ("What is multicollinearity in statistical regression?",
         ["High correlation between the dependent and independent variables", "High correlation between two or more independent (predictor) variables", "Non-constant variance of residuals", "Lack of normal distribution in errors"], "B",
         "Multicollinearity occurs when independent predictors are strongly linearly correlated with each other."),
        ("What is Homoscedasticity?",
         ["Residuals having constant variance across all levels of independent variables", "Non-linear relationship between features", "Outliers in the target variable", "Bimodal distribution of predictors"], "A",
         "Homoscedasticity refers to equal/constant error variance across predictor ranges."),
        ("What metric measures the proportion of variance in the dependent variable explained by independent variables?",
         ["Pearson r", "Coefficient of Determination (R-squared)", "Standard error", "F-statistic"], "B",
         "R-squared represents the proportion of total variance explained by the regression model."),
        ("What is a Z-score?",
         ["The distance of a value from the mean measured in standard deviation units", "The median divided by the variance", "The probability of an outlier", "The degrees of freedom"], "A",
         "Z = (X - mu) / sigma, representing normalized distance from the population mean."),
        ("Which distribution has heavier tails than the normal distribution and is used when sample size is small with unknown population variance?",
         ["Student's t-distribution", "Uniform distribution", "Exponential distribution", "Chi-Square distribution"], "A",
         "Student's t-distribution has fatter tails to account for greater uncertainty with small sample sizes."),
        ("What does a Chi-Square Test of Independence assess?",
         ["Differences between two numerical means", "Association between two categorical variables", "Normality of a dataset", "Homogeneity of regression coefficients"], "B",
         "Chi-square test of independence tests whether categorical variables are statistically independent."),
        ("If a distribution is right-skewed (positively skewed), what is the typical relationship between mean, median, and mode?",
         ["Mean < Median < Mode", "Mode < Median < Mean", "Mean = Median = Mode", "Median < Mode < Mean"], "B",
         "In right-skewed distributions, the long tail pulls the Mean to the right: Mode < Median < Mean.")
    ]

    # 5. MACHINE LEARNING (20 Questions)
    ml_q = [
        ("What problem occurs when a model performs exceptionally well on training data but poorly on unseen test data?",
         ["Underfitting", "Overfitting", "Data drift", "Imbalanced classes"], "B",
         "Overfitting occurs when a model memorizes noise in training data, harming generalization."),
        ("Which of the following is a supervised learning task?",
         ["K-Means Clustering", "Predicting house prices using Linear Regression", "Principal Component Analysis (PCA)", "Association Rule Mining"], "B",
         "Supervised learning trains on labeled target variables, like continuous house price prediction."),
        ("What is the trade-off in the Bias-Variance dilemma?",
         ["High bias causes underfitting; high variance causes overfitting", "High bias causes overfitting; high variance causes underfitting", "Bias and variance must always sum to 1", "Bias only applies to neural networks"], "A",
         "High bias implies overly simplistic assumptions (underfit); high variance implies hypersensitivity to noise (overfit)."),
        ("Which metric is most suitable for evaluating a classification model with highly imbalanced classes?",
         ["Accuracy", "F1-Score / PR-AUC", "Mean Squared Error", "R-squared"], "B",
         "F1-score (harmonic mean of precision & recall) balances false positives and false negatives without accuracy paradox."),
        ("How does Random Forest reduce the variance of individual Decision Trees?",
         ["By boosting errors sequentially", "By bagging (bootstrap aggregating) and random feature subspace selection", "By pruning the trees to depth 1", "By using L1 regularization"], "B",
         "Random Forest trains diverse trees on bootstrap samples with random feature splits, averaging predictions to reduce variance."),
        ("What does L1 (Lasso) regularization do to model coefficients that L2 (Ridge) does not?",
         ["It shrinks coefficients smoothly without zeroing them", "It can shrink coefficients strictly to zero, performing automatic feature selection", "It squares the weights in the penalty term", "It doubles training speed"], "B",
         "Lasso adds |w| penalty, forcing uninformative feature coefficients exactly to zero."),
        ("What is the primary role of cross-validation (e.g., 5-fold CV)?",
         ["To speed up gradient descent convergence", "To reliably estimate generalization performance and detect overfitting", "To artificially increase sample size", "To clean corrupted CSV rows"], "B",
         "Cross-validation rotates validation folds to yield robust estimates of model generalization error."),
        ("What is Data Leakage in a machine learning pipeline?",
         ["Saving model weights in plaintext", "Accidentally sharing information from outside the training dataset (such as test set or future data) during model training", "Hardware RAM running out of memory", "Network packet drops during training"], "B",
         "Data leakage occurs when test information bleeds into preprocessing or training, creating misleadingly optimistic evaluation."),
        ("In Logistic Regression, what mathematical function maps any real-valued number into a probability between 0 and 1?",
         ["ReLU function", "Sigmoid (Logistic) function", "Tanh function", "Softplus function"], "B",
         "The sigmoid function sigma(z) = 1 / (1 + e^-z) squashes linear combination z into [0, 1]."),
        ("What distance metric is standardly used by default in K-Nearest Neighbors (KNN)?",
         ["Cosine Distance", "Euclidean Distance", "Manhattan Distance", "Hamming Distance"], "B",
         "Standard KNN implementations default to Euclidean distance: sqrt(sum((x_i - y_i)^2))."),
        ("Why is feature scaling essential for distance-based algorithms like KNN and SVM?",
         ["Because features with larger numerical magnitudes will dominate distance calculations", "Scaling increases dataset memory size", "Distance algorithms fail on scaled features", "It is only necessary for decision trees"], "A",
         "Without scaling, a feature spanning 0-100,000 dominates features spanning 0-1 regardless of predictive importance."),
        ("What is the purpose of pruning in Decision Trees?",
         ["To increase training accuracy", "To remove branches that provide little power to prevent overfitting", "To convert regression tree to classification", "To calculate gradient vectors"], "B",
         "Pruning simplifies complex tree structures to improve generalization on unseen test data."),
        ("What does the ROC-AUC score measure?",
         ["The area under the receiver operating characteristic curve across all classification thresholds", "The accuracy of regression residuals", "The training speed per epoch", "The percentage of missing values"], "A",
         "ROC-AUC measures the classifier's ability to rank positive instances above negative instances across thresholds."),
        ("Which algorithm works by sequentially training weak learners to correct errors of predecessor models?",
         ["Random Forest", "Bagging Classifier", "Gradient Boosting / AdaBoost", "K-Means"], "C",
         "Boosting sequentially fits new models to the pseudo-residuals of previous learners."),
        ("What is the Confusion Matrix element representing cases where the model predicted negative, but the true class was positive?",
         ["True Positive (TP)", "False Positive (FP)", "False Negative (FN)", "True Negative (TN)"], "C",
         "False Negative (Type II error) is an actual positive incorrectly labeled as negative."),
        ("What does Precision measure in classification?",
         ["TP / (TP + FP) — What proportion of predicted positives was truly correct", "TP / (TP + FN) — What proportion of actual positives was identified", "TN / (TN + FP)", "Total correct predictions / Total samples"], "A",
         "Precision measures the veracity of positive predictions: TP / (TP + FP)."),
        ("What does Recall (Sensitivity) measure in classification?",
         ["TP / (TP + FP)", "TP / (TP + FN) — What proportion of actual positive cases was captured", "FP / (FP + TN)", "TN / (TN + FN)"], "B",
         "Recall measures the model's coverage of real positive instances: TP / (TP + FN)."),
        ("Which method decomposes high-dimensional feature spaces into orthogonal axes maximizing variance?",
         ["K-Means", "Principal Component Analysis (PCA)", "Linear Regression", "DBSCAN"], "B",
         "PCA finds orthogonal linear combinations of features that capture maximum variance."),
        ("What is Hyperparameter Tuning?",
         ["Optimizing model parameters learned automatically during backpropagation", "Searching for optimal configuration parameters set prior to training (like learning rate, tree depth)", "Formatting JSON configuration files", "Cleaning dirty CSV datasets"], "B",
         "Hyperparameters are external configuration knobs (e.g. max_depth, n_neighbors) optimized via Grid/Random search."),
        ("Why should feature scaling (e.g., StandardScaler) be fitted only on training data and transformed on test data?",
         ["To prevent data leakage of test set distribution statistics into the training process", "Because test sets cannot be transformed", "StandardScaler works only on training sets", "To make the model run faster"], "A",
         "Fitting on the whole dataset introduces test set mean and standard deviation into the training phase, violating generalization validity.")
    ]

    # 6. POWER BI (20 Questions)
    pbi_q = [
        ("What language is used in Power BI to create custom calculated columns and measures?",
         ["Python", "M", "DAX (Data Analysis Expressions)", "SQL"], "C",
         "DAX is the formula expression language used for custom calculations and aggregations in Power BI."),
        ("What language is used in Power Query for data transformation and ETL?",
         ["DAX", "M Language", "R", "C#"], "B",
         "Power Query transformations are recorded and executed in the M formula language."),
        ("What is the key difference between a Calculated Column and a Measure in Power BI?",
         ["Calculated columns are evaluated row-by-row and stored in RAM; Measures are calculated dynamically on aggregate in the visual filter context", "Measures consume more disk space than calculated columns", "Calculated columns are dynamic; Measures are static", "There is no difference"], "A",
         "Calculated columns expand table footprint in memory; measures compute on-the-fly based on visual context."),
        ("What DAX function modifies the evaluation filter context of an expression?",
         ["SUM()", "CALCULATE()", "FILTER()", "RELATED()"], "B",
         "CALCULATE evaluates an expression in an altered or overridden filter context."),
        ("Which data modeling schema is strongly recommended as best practice in Power BI?",
         ["Flat wide table", "Star Schema (Fact and Dimension tables)", "Normalized 3NF relational schema", "Network graph schema"], "B",
         "Star schemas optimize Power BI's VertiPaq columnar in-memory storage engine and relationship traversals."),
        ("What does the `RELATED()` function in DAX do?",
         ["Fetches a related value from another table connected by an active relationship", "Calculates correlation between two columns", "Creates a new relationship automatically", "Filters unrelated tables"], "A",
         "RELATED() retrieves a value from a related dimension table along an active relationship."),
        ("What is the purpose of Power BI's Power Query Editor?",
         ["Design reports and visual dashboards", "Extract, Transform, and Load (ETL) data before loading into the model", "Manage Azure workspace permissions", "Write DAX measures"], "B",
         "Power Query is the ETL interface for ingestion, cleansing, pivoting, and shaping raw data."),
        ("Which visual is most effective for visualizing the composition of a metric through sequential positive and negative changes?",
         ["Scatter Plot", "Waterfall Chart", "Gauge Chart", "Treemap"], "B",
         "Waterfall charts display cumulative running totals as values are added or subtracted."),
        ("What is Row-Level Security (RLS) used for in Power BI?",
         ["Encrypting the database hard drive", "Restricting data access for specific users based on role filters", "Compressing column size", "Speeding up network queries"], "B",
         "RLS restricts data visibility so users only see rows allowed by their security role filter."),
        ("What is the difference between DirectQuery and Import mode in Power BI?",
         ["Import caches data in memory for rapid response; DirectQuery queries the underlying source dynamically in real time", "DirectQuery is always faster than Import", "Import mode cannot refresh data", "DirectQuery stores data on local desktop"], "A",
         "Import stores compressed columnar data in VertiPaq engine; DirectQuery pushes queries down to the source live."),
        ("What feature allows report viewers to dynamically slice and filter visuals on a page by date or category?",
         ["Slicer", "KPI Card", "Tooltip", "Matrix"], "A",
         "Slicers are on-canvas visual controls allowing users to filter other visuals on the report page."),
        ("What DAX function returns the current row count of a table or filtered table?",
         ["COUNT()", "COUNTROWS()", "DISTINCTCOUNT()", "SUM()"], "B",
         "COUNTROWS(table) counts the number of rows in the specified table or table expression."),
        ("What is a Cardinality setting in Power BI relationships?",
         ["The direction of data compression", "The nature of the relationship: One-to-Many, Many-to-One, One-to-One, or Many-to-Many", "The number of measures on a page", "The color palette scheme"], "B",
         "Cardinality describes the multiplicity of keys across related tables (e.g. 1:*, *:1)."),
        ("What does cross-filter direction 'Both' mean in a relationship?",
         ["Filters applied to either table propagate across the relationship to filter the other", "Only dimension filters fact", "Both tables are duplicated", "Queries run twice"], "A",
         "Bi-directional filtering allows filters to travel in both directions across the relationship."),
        ("What visual is best for comparing values across two categorical dimensions with hierarchical tiles?",
         ["Donut chart", "Treemap", "Line chart", "Funnel chart"], "B",
         "Treemaps visualize hierarchical nested rectangles proportional to quantitative metrics."),
        ("How do you prevent a specific visual from being affected when a slicer selection changes?",
         ["Format > Edit Interactions > Select 'None'", "Delete the visual", "Hide the visual in selection pane", "Lock the slicer"], "A",
         "Edit Interactions enables configuring whether an interaction filters, highlights, or does nothing."),
        ("What DAX function is used to ignore all filters on a column or table?",
         ["REMOVE()", "ALL()", "KEEPFILTERS()", "CLEAR()"], "B",
         "ALL() removes all filter context from specified columns or tables, commonly used in denominator calculations."),
        ("What is a Power BI Workspace?",
         ["A local folder on Windows Desktop", "A shared collaborative cloud container in Power BI Service for dashboards, reports, and datasets", "A Python script environment", "A database backup file"], "B",
         "Workspaces are shared containers in Power BI Service for publishing, collaborating, and distributing artifacts."),
        ("What is Drillthrough in Power BI reports?",
         ["A navigation action taking users to a focused detail page filtered to the selected entity", "Drilling a hole in a pie chart", "Exporting data to CSV", "Importing data from SQL server"], "A",
         "Drillthrough navigates to a designated destination page focused specifically on the clicked entity context."),
        ("Which visual shows progress toward a measurable target or quota?",
         ["Gauge / KPI Visual", "Scatter Plot", "Sankey Diagram", "Ribbon Chart"], "A",
         "Gauge and KPI visuals clearly display current values against minimum, target, and maximum thresholds.")
    ]

    # 7. COMMUNICATION (20 Questions)
    comm_q = [
        ("When presenting complex machine learning findings to non-technical business stakeholders, what is the best practice?",
         ["Use detailed mathematical formulas and loss curves", "Focus on business value, key insights, and actionable recommendations using clear domain language", "Skip the presentation and send the raw Python script", "Speak strictly in statistical jargon"], "B",
         "Business leaders prioritize bottom-line impact, risk, and ROI over algorithm internals."),
        ("What is Active Listening in a workplace collaboration setting?",
         ["Waiting patiently for your turn to speak", "Fully concentrating, understanding, responding, and thoughtfully summarizing what the speaker said", "Recording the audio meeting secretly", "Nodding continuously without speaking"], "B",
         "Active listening involves intentional comprehension, clarifying questions, and validation."),
        ("What is the primary purpose of the 'STAR' technique in behavioral job interviews?",
         ["Structure answers logically using Situation, Task, Action, and Result", "State Technical Acronyms Rapidly", "Score Top Applicant Ratings", "Show Transparent Academic Records"], "A",
         "STAR provides a clear, structured storytelling framework for competency questions."),
        ("What does the '7 Cs' of effective professional communication include?",
         ["Clear, Concise, Concrete, Correct, Coherent, Complete, Courteous", "Complex, Casual, Cryptic, Critical, Clever, Consistent, Constant", "Coding, Calculating, Computing, Connecting, Converting, Checking, Caching", "None of the above"], "A",
         "The 7 Cs ensure clarity, efficiency, and professional etiquette in workplace communication."),
        ("In email communication, what is the most appropriate way to deliver constructive project feedback?",
         ["Publicly email all team members highlighting mistakes in uppercase", "Be specific, objective, respectful, focus on the work rather than personal traits, and suggest next steps", "Send vague complaints without examples", "Avoid mentioning any areas for improvement"], "B",
         "Effective feedback is constructive, actionable, objective, and psychologically safe."),
        ("When creating slides for an executive presentation, what is the '10/20/30 Rule' popularized by Guy Kawasaki?",
         ["10 slides, 20 minutes duration, minimum 30-point font size", "10 topics, 20 visuals, 30 paragraphs", "10 equations, 20 data tables, 30 slides", "10 colors, 20 icons, 30 seconds per slide"], "A",
         "The rule advocates simplicity: 10 slides, 20 minutes, 30-pt font to prevent text overcrowding."),
        ("What is non-verbal communication?",
         ["Writing long emails", "Body language, facial expressions, eye contact, and tone of voice", "Communicating using only SQL scripts", "Silent telepathy"], "B",
         "Non-verbal communication conveys subtle emotional cues and engagement without spoken words."),
        ("How should a data professional handle a situation where a stakeholder requests an unrealistic project deadline?",
         ["Agree immediately and burn out", "Communicate transparently, present data-driven effort estimates, and negotiate scoped deliverables or phased milestones", "Ignore the stakeholder's messages", "Complain on social media"], "B",
         "Professional diplomacy pairs realistic transparency with constructive phased solutions."),
        ("What is the primary purpose of an 'Executive Summary' in a technical report?",
         ["Provide a concise high-level synthesis of problem, findings, and recommendations for busy decision-makers", "List all Python dependencies and versions", "Include full database schema DDL", "Show raw CSV output"], "A",
         "Executive summaries distill the core thesis and actionable takeaways into a single readable page."),
        ("In conflict resolution between team members, what is the recommended first step?",
         ["Escalate immediately to senior management", "Clarify the core issue objectively through open dialogue and identify shared common goals", "Avoid speaking to each other", "Cast a public vote on who is right"], "B",
         "De-escalation begins with objective fact-finding and identifying shared objectives."),
        ("What makes a data visualization story effective for business audiences?",
         ["Using 3D pie charts with 20 distinct bright colors", "A clear narrative, purposeful chart selection, highlighted key insights, and minimal clutter", "Packing as many charts on one page as possible", "Omitting axis labels to save space"], "B",
         "Data storytelling connects visual clarity with a purposeful narrative and decluttered layout."),
        ("What is the best way to open a technical presentation to capture audience interest?",
         ["Start with a 10-minute autobiography", "State the core problem statement, why it matters to the organization, and what solution will be revealed", "Read code line by line", "Apologize for being nervous"], "B",
         "Hooking the audience requires articulating relevance and strategic value immediately."),
        ("What does 'Empathy' in stakeholder management mean?",
         ["Agreeing to every request without question", "Understanding the stakeholder's priorities, pain points, pressures, and perspective", "Feeling sorry for other departments", "Offering financial compensation"], "B",
         "Empathy aligns analytical solutions with the authentic operational pressures stakeholders face."),
        ("How should you respond to a challenging technical question during an interview or presentation if you do not know the answer?",
         ["Fabricate an answer confidently", "Honestly acknowledge you do not know, explain your thought process on how you would investigate it, and offer to follow up", "Change the subject quickly", "Argue with the interviewer"], "B",
         "Intellectual honesty coupled with structured analytical curiosity demonstrates integrity and maturity."),
        ("Why is 'Conciseness' valued in written business communication?",
         ["It respects the reader's time and delivers the message with maximum impact and minimum ambiguity", "It shows the writer does not know details", "Short messages are always informal", "It prevents grammar checks"], "A",
         "Concise writing eliminates bloat while preserving clarity and essential facts."),
        ("What is the purpose of a Daily Standup meeting in Agile/Scrum?",
         ["Deliver a 2-hour technical lecture", "Briefly share what was accomplished yesterday, what is planned today, and any blocking obstacles", "Conduct formal performance evaluations", "Assign blames for sprint bugs"], "B",
         "Standups provide rapid alignment on progress and immediate identification of bottlenecks."),
        ("What is the best strategy when communicating with someone who has an aggressive communication style?",
         ["Respond with equal aggression", "Stay calm, maintain professional composure, focus strictly on facts, and set respectful boundaries", "Leave the company immediately", "Agree to invalid claims"], "B",
         "De-escalating aggression requires calm neutrality and factual grounding."),
        ("Which of the following demonstrates strong intercultural communication competence?",
         ["Assuming all cultures communicate identically to your own", "Being culturally sensitive, patient, attentive to communication norms, and avoiding culture-specific slang", "Using complex regional idioms", "Speaking louder when people don't understand"], "B",
         "Global teamwork thrives on adaptability, patience, and inclusive phrasing."),
        ("What does the 'Pyramid Principle' in business communication suggest?",
         ["Start with the core conclusion or recommendation first, then support it with grouped arguments and supporting data", "Start with raw data and reveal the answer only at the very end", "Communicate only in triangular diagrams", "Hierarchy determines whose opinion is right"], "A",
         "Developed by Barbara Minto at McKinsey, top-down structure accelerates comprehension."),
        ("How should technical documentation (such as a README or API doc) be written?",
         ["Cryptically to protect proprietary logic", "Clear, structured, reproducible, with prerequisites, installation steps, and code examples", "Only with screenshots, no text", "As an unstructured single paragraph"], "B",
         "High-quality documentation empowers seamless onboarding, reproducibility, and longevity.")
    ]

    # 8. APTITUDE & LOGICAL REASONING (20 Questions)
    apt_q = [
        ("A train running at 72 km/h crosses a pole in 15 seconds. What is the length of the train?",
         ["250 meters", "300 meters", "350 meters", "200 meters"], "B",
         "Speed = 72 * (5/18) = 20 m/s. Length = Speed * Time = 20 * 15 = 300 meters."),
        ("If A can complete a work in 10 days and B in 15 days, in how many days can both complete it working together?",
         ["5 days", "6 days", "8 days", "7.5 days"], "B",
         "Combined rate = 1/10 + 1/15 = 5/30 = 1/6. Hence, 6 days."),
        ("Find the next number in the series: 3, 7, 15, 31, 63, ...",
         ["95", "127", "120", "125"], "B",
         "Pattern: Multiply by 2 and add 1 (x * 2 + 1). 63 * 2 + 1 = 127."),
        ("A shopkeeper sells an article for $480 at a profit of 20%. What was the cost price?",
         ["$380", "$400", "$420", "$440"], "B",
         "Selling Price = 1.20 * CP => CP = 480 / 1.2 = $400."),
        ("In a class of 60 students, 40% are girls. How many boys are there in the class?",
         ["24", "36", "30", "28"], "B",
         "Girls = 60 * 0.40 = 24. Boys = 60 - 24 = 36 boys."),
        ("Find the odd one out: 27, 64, 125, 144, 216",
         ["64", "125", "144", "216"], "C",
         "27=3^3, 64=4^3, 125=5^3, 216=6^3 are perfect cubes. 144 is 12^2 (not a cube)."),
        ("If 'CAT' is coded as '3120', how is 'DOG' coded using alphabetical positional values (A=1, B=2...)?",
         ["4157", "4147", "3157", "4167"], "A",
         "D=4, O=15, G=7 => 4157."),
        ("A bag contains 5 red, 4 blue, and 3 green marbles. What is the probability of randomly drawing a blue marble?",
         ["1/3", "4/12 (1/3)", "5/12", "1/4"], "B",
         "Total marbles = 5 + 4 + 3 = 12. P(Blue) = 4/12 = 1/3."),
        ("The average of 5 consecutive odd numbers is 25. What is the smallest of these numbers?",
         ["21", "23", "25", "19"], "A",
         "Consecutive odd numbers centered at 25: 21, 23, 25, 27, 29. Smallest is 21."),
        ("A sum of $1,000 is invested at 10% per annum simple interest for 3 years. What is the total interest earned?",
         ["$300", "$331", "$250", "$310"], "A",
         "SI = (P * R * T) / 100 = (1000 * 10 * 3) / 100 = $300."),
        ("If North becomes South-East, what does West become?",
         ["North-East", "South-West", "North-West", "East"], "A",
         "Turning 135 degrees clockwise: West + 135 deg clockwise = North-East."),
        ("Pointing to a photograph, a man said, 'She is the daughter of my grandfather's only son.' Who is she to the man?",
         ["Mother", "Sister", "Aunt", "Niece"], "B",
         "Grandfather's only son is the man's father. Father's daughter is his sister."),
        ("Two dice are thrown simultaneously. What is the probability of getting a sum equal to 7?",
         ["1/6", "1/12", "5/36", "7/36"], "A",
         "Pairs summing to 7: (1,6), (2,5), (3,4), (4,3), (5,2), (6,1) = 6 outcomes. 6/36 = 1/6."),
        ("What is 15% of 240 plus 25% of 120?",
         ["66", "60", "72", "68"], "A",
         "15% of 240 = 36. 25% of 120 = 30. 36 + 30 = 66."),
        ("A pipe can fill a tank in 4 hours, while another pipe empties it in 6 hours. If both are opened, how long to fill the tank?",
         ["10 hours", "12 hours", "8 hours", "15 hours"], "B",
         "Net rate = 1/4 - 1/6 = (3 - 2)/12 = 1/12. Time = 12 hours."),
        ("In how many different ways can the letters of the word 'DATA' be arranged?",
         ["24", "12", "6", "4"], "B",
         "Word length = 4, 'A' repeats twice. Permutations = 4! / 2! = 24 / 2 = 12 ways."),
        ("A car travels the first half of a journey at 40 km/h and the second half at 60 km/h. What is the average speed?",
         ["50 km/h", "48 km/h", "52 km/h", "45 km/h"], "B",
         "Harmonic mean: 2 * S1 * S2 / (S1 + S2) = 2 * 40 * 60 / 100 = 48 km/h."),
        ("Complete the analogy: Book : Pages :: Library : ?",
         ["Librarian", "Books", "Shelves", "Reading"], "B",
         "A book is composed of pages; a library is composed of books."),
        ("If 5 cats can catch 5 mice in 5 minutes, how many cats are needed to catch 100 mice in 100 minutes?",
         ["100", "5", "20", "50"], "B",
         "1 cat catches 1 mouse in 5 minutes. In 100 minutes, 1 cat catches 20 mice. To catch 100 mice: 100 / 20 = 5 cats."),
        ("At what time between 3 and 4 o'clock will the hands of a clock be together (overlap)?",
         ["3:15:00", "16 and 4/11 minutes past 3", "15 and 5/11 minutes past 3", "3:18:00"], "B",
         "Theta = |30H - 5.5M| = 0 => 30*3 = 5.5M => M = 90 / 5.5 = 180 / 11 = 16 4/11 minutes past 3.")
    ]

    skill_banks = {
        "Python": ("PY", py_q),
        "SQL": ("SQL", sql_q),
        "Excel": ("EXCEL", excel_q),
        "Statistics": ("STAT", stat_q),
        "Machine Learning": ("ML", ml_q),
        "Power BI": ("PBI", pbi_q),
        "Communication": ("COMM", comm_q),
        "Aptitude": ("APT", apt_q)
    }

    for skill_name, (prefix, q_list) in skill_banks.items():
        for idx, (question, options, correct_ans, explanation) in enumerate(q_list, 1):
            q_id = f"{prefix}_{idx:02d}"
            questions.append({
                "id": q_id,
                "skill": skill_name,
                "question": question,
                "options": options,
                "correct_answer": correct_ans,
                "explanation": explanation
            })

    return questions

def save_questions(output_path: str = None):
    if output_path is None:
        base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        output_path = os.path.join(base_dir, "data", "questions", "assessment_questions.json")
    
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    questions = create_questions_bank()
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(questions, f, indent=2, ensure_ascii=False)
    
    print(f"[OK] Successfully saved {len(questions)} questions across 8 skills to: {output_path}")

if __name__ == "__main__":
    save_questions()
